var speakersData = [
  {
    "slug": "alexander-minchev",
    "title": "Alexander Minchev - BSTF 2026",
    "metaDesc": "BSTF 2026 - Alexander Minchev, Founder &amp; MD @ AbsCloud / Abilix Soft",
    "name": {
      "bg": "Александър Минчев",
      "en": "Alexander Minchev"
    },
    "role": {
      "bg": "Founder &amp; MD @ AbsCloud / Abilix Soft",
      "en": "Founder &amp; MD @ AbsCloud / Abilix Soft"
    },
    "track": {
      "bg": "Изкуствен интелект",
      "en": "Artificial Intelligence"
    },
    "topic": {
      "bg": "Облачна инфраструктура, AI и киберсигурност",
      "en": "Cloud infrastructure, AI &amp; cybersecurity"
    },
    "bio": {
      "bg": "Alexander Minchev е основател и управляващ директор на Abilix Soft Ltd. Работи професионално със сървъри повече от 25 години — от края на миналото хилядолетие, както той обича да казва. Под негово ръководство Abilix Soft се специализира в предоставянето на висококачествени облачни решения за бизнес клиенти, предлагани под марката AbsCloud. През април 2025 г. обновеният дата център на компанията във Варна отвори врати за външни клиенти под бранда AC DC (AbsCloud Data Center). Проектът се откроява с концепцията си за улавяне на топлината, генерирана от сървърите в дата центъра, и съхраняването ѝ в специализирани контейнери за последващо използване в градската отоплителна система. Паралелно с това Alexander Minchev работи върху докторска дисертация в областта на изкуствения интелект и сигурността. Той е посветен на запазването на предния фронт на технологичния прогрес и използването на изкуствен интелект за подобряване на киберсигурността.",
      "en": "Alexander Minchev is the founder and managing director of Abilix Soft Ltd. He has been working professionally with servers for over 25 years, or, as he likes to put it, since the end of the last millennium. Under his leadership, Abilix Soft has specialized in providing high-quality cloud solutions for business clients, offered under the AbsCloud brand. In April 2025, the company's renovated data center in Varna opened its doors to external clients under the brand AC DC (AbsCloud Data Center). The project stands out for its concept of harnessing the heat generated by the servers in the Data Center and storing it in specialized containers for subsequent use in the city's district heating system. In parallel, Alexander Minchev is working on a doctoral dissertation in artificial intelligence and security. He is dedicated to staying at the forefront of technological progress and to leveraging artificial intelligence to enhance cybersecurity."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "alexander-minchev.jpg"
  },
  {
    "slug": "andrey-lilov",
    "title": "Андрей Лилов - BSTF 2026",
    "metaDesc": "BSTF 2026 - Андрей Лилов, Co-founder &amp; CEO @ URBO Studio",
    "name": {
      "bg": "Андрей Лилов",
      "en": "Andrey Lilov"
    },
    "role": {
      "bg": "Co-founder &amp; CEO @ URBO Studio",
      "en": "Co-founder &amp; CEO @ URBO Studio"
    },
    "track": {
      "bg": "Умен град",
      "en": "Smart City"
    },
    "topic": {
      "bg": "Дигитализация на туризма и събитийната индустрия",
      "en": "Digitalization of tourism &amp; events industry"
    },
    "bio": {
      "bg": "URBO Studio е софтуерна компания, работеща в сферата на туризма и умната градска инфраструктура. От повече от 11 години компанията разработва цялостни системи за резервации, билетиране и разплащания, маркетингови инструменти и контрол на достъпа, помагайки на бизнеса да оптимизира търговските си процеси и да повиши оперативната ефективност. С над 2 000 клиенти в България и 10+ индустрии и интеграции с водещи партньори, URBO Studio е доверен избор за бизнеса и общините, търсещи иновации, мащабируемост и устойчив растеж. Андрей Лилов е съосновател и CEO на URBO Studio - технологична компания, разработваща решения за дигитализация, продажби и управление в туризма, събитията, културата, спорта и развлекателната индустрия. Той има богат опит в бизнес развитието, хотелския софтуер, продажбите и създаването на дигитални платформи, които свързват бизнеса с клиентите му по по-пряк и ефективен начин. Под негово ръководство URBO Studio разработва решения за онлайн билетиране, резервации, плащания, контрол на достъпа, QR базирани продажби и туристически платформи за общини и туристически обекти, музеи, атракции, хотели и организатори на събития. Днес Андрей е фокусиран върху следващия етап от развитието на URBO Studio - интеграцията на AI, автоматизацията и нови модели за достъп, продажби и управление на изживяванията.",
      "en": "URBO Studio is a software solutions provider operating in the fields of tourism and smart urban infrastructure. For more than 11 years, the company has been developing end-to-end systems for reservation, ticketing and payment management, marketing tools and access control, helping businesses optimize their commercial processes and improve operational efficiency. With over 2,000 clients in Bulgaria across 10+ industries and integrations with leading partners, URBO Studio is a trusted choice for businesses and municipalities looking for innovation, scalability and sustainable growth. Andrey Lilov is Co-founder and CEO of URBO Studio - a technology company developing solutions for digitalization, sales and management in tourism, events, culture, sports and the entertainment industry. He has extensive experience in business development, hospitality software, sales and the creation of digital platforms that connect businesses with their customers in a more direct and efficient way. Under his leadership, URBO Studio develops solutions for online ticketing, reservations, payments, access control, QR-based sales, and tourism platforms for municipalities and tourism sites, museums, attractions, hotels and event organizers. Today, Andrey is focused on the next stage of URBO Studio's development - the integration of AI, automation and new models for access, sales and experience management."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "andrey-lilov.jpg"
  },
  {
    "slug": "anton-tonchev",
    "title": "проф. Антон Тончев - BSTF 2026",
    "metaDesc": "BSTF 2026 - проф. Антон Тончев, Professor &amp; Chair, Anatomy @ Medical University Varna",
    "name": {
      "bg": "проф. Антон Тончев",
      "en": "Prof. Anton Tonchev"
    },
    "role": {
      "bg": "Professor &amp; Chair, Anatomy @ Medical University Varna",
      "en": "Professor &amp; Chair, Anatomy @ Medical University Varna"
    },
    "track": {
      "bg": "Биотехнологии",
      "en": "BioTech"
    },
    "topic": {
      "bg": "Стволови клетки на мозъка: от изследвания към терапия",
      "en": "Brain stem cell niches: from research to therapy"
    },
    "bio": {
      "bg": "Проф. Антон Тончев завършва Медицина в Медицински университет - Варна. Докторантурата си извършва в Университета в Каназава, Япония, изучавайки неврогенеза и глиогенеза при маймуни след церебрална исхемия. Бил е постдокторант на фондация „Александър фон Хумболт” в Института за биофизична химия „Макс Планк” в Гьотинген, Германия, изучавайки генетични механизми на неврогенезата при възрастни. От 2012 г. е ръководител на Катедрата по анатомия и клетъчна биология във Варна, а от 2018 г. - директор на Научноизследователския институт на Медицински университет - Варна. Неговата група във Варна изучава стволовите клетъчни ниши на мозъка с фокус върху примати и хора.",
      "en": "Professor in Anatomy and Neurobiology at Medical University - Varna. Anton B. Tonchev has graduated in Medicine at the Medical University - Varna. He has done his PhD work at the University of Kanazawa, Japan, studying neurogenesis and gliogenesis in monkeys following cerebral ischemia. He has been postdoctoral fellow of the Alexander von Humboldt Foundation at the Max Planck Institute for Biophysical Chemistry, Goettingen Germany studying genetic mechanisms of adult neurogenesis. Since 2012 he has served as a Chair at the Department of Anatomy and Cell Biology in Varna, and since 2018 - as a Director of the Research Institute of the Medical University - Varna. His group in Varna is studying the brain stem cell niches with a focus on primates and humans."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "anton-tonchev.webp"
  },
  {
    "slug": "cemile-usta",
    "title": "Cemile Köseler Usta - BSTF 2026",
    "metaDesc": "BSTF 2026 - Cemile Köseler Usta, Innovation Specialist @ Istanbul Chamber of Industry",
    "name": {
      "bg": "Cemile Köseler Usta",
      "en": "Cemile Köseler Usta"
    },
    "role": {
      "bg": "Innovation Specialist @ Istanbul Chamber of Industry",
      "en": "Innovation Specialist @ Istanbul Chamber of Industry"
    },
    "track": {
      "bg": "Умен град",
      "en": "Smart City"
    },
    "topic": {
      "bg": "Иновации и дигитална трансформация: турско-българско сътрудничество",
      "en": "Innovation &amp; digital transformation: Turkey-Bulgaria cooperation"
    },
    "bio": {
      "bg": "Cemile Köseler Usta започва професионалната си кариера в компания за производство на полимерни композити, като участва в проекти за подобрение на процесите и R&amp;D. Придобива опит в контрола на качеството, оценката на клиентски жалби, финансиране на R&amp;D проекти, одитиране на системи за качество и околна среда. След това работи за Dizayn Group като мениджър на международни инфраструктурни проекти, придобивайки опит в писането на оферти за международни търгове, експортни процеси, организиране на обучения и презентации за клиенти, както и участие в международни маркетингови събития. От 2009 г. работи в Истанбулската камара на индустрията, специализирайки в информиране, обратна връзка, консултации относно иновации и дигитална трансформация, достъп до финансиране, предприемачество, брокерски услуги и трансфер на технологии за индивидуални клиенти, както и организиране на конгреси, обучения и B2B събития.",
      "en": "Cemile started her professional career at a polymeric composites producing company as taking part in the company's process improvement and R&amp;D projects. She gained experience in quality control, evaluation of customer complaints, R&amp;D Projects funding, Quality and Environment Systems auditing there. She then worked for Dizayn Group as International Infrastructure Projects Manager. She gained experience in writing proposals for international tenders, export processes, organizing trainings and presentations for the customers, organizing participations to international marketing events, representing the company during the meetings with Water Ministries of several countries. She has been working in Istanbul Chamber of Industry since 2009 specializing on informing, feedback, consultancy on innovation and digital transformation, access to finance, entrepreneurship, brokerage and technology transfer services to individual clients as well as organization of congress, education, B2B events."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "cemile-usta.webp"
  },
  {
    "slug": "dimitar-karlovski",
    "title": "Dimitar Karlovski - BSTF 2026",
    "metaDesc": "BSTF 2026 - Dimitar Karlovski, Founder @ Mitotopia",
    "name": {
      "bg": "Dimitar Karlovski",
      "en": "Dimitar Karlovski"
    },
    "role": {
      "bg": "Founder @ Mitotopia",
      "en": "Founder @ Mitotopia"
    },
    "track": {
      "bg": "Биотехнологии",
      "en": "BioTech"
    },
    "topic": {
      "bg": "Митохондриите като Chi: May the Force be with you",
      "en": "Mitochondria as Chi: May the Force be with you"
    },
    "bio": {
      "bg": "Mitotopia е стартъп, разработващ продукти и услуги, насърчаващи митохондриалното здраве в репродукцията, спорта и дълголетието. Митохондриите са много повече от енергийните централи на клетките - те са координатори на клетъчната биохимия. Клиничната практика може да генерира идеи и да адресира проблеми, а използвайки наука и изследвания, идеите могат да се превърнат в бъдещи решения, които след това да се приложат обратно в практиката.",
      "en": "Mitotopia is a start-up developing products and services promoting mitochondrial health in reproduction, sports and longevity. Mitochondria are much more than the powerhouses of the cells. They are coordinators of cellular biochemistry. Clinical practice can generate ideas and address problems. When using science and research, ideas can be turned into prospective solutions, and solutions could then be applied back into practice."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "dimitar-karlovski.jpg"
  },
  {
    "slug": "dragomir-vatkov",
    "title": "Dragomir Vatkov - BSTF 2026",
    "metaDesc": "BSTF 2026 - Dragomir Vatkov, Lead Cyber Security Architect, SABSA",
    "name": {
      "bg": "Dragomir Vatkov",
      "en": "Dragomir Vatkov"
    },
    "role": {
      "bg": "Lead Cyber Security Architect, SABSA",
      "en": "Lead Cyber Security Architect, SABSA"
    },
    "track": {
      "bg": "Киберсигурност",
      "en": "Cybersecurity"
    },
    "topic": {
      "bg": "Невидимата архитектура: как основите на киберсигурността определят устойчивостта",
      "en": "The Invisible Architecture: How Cyber Security Foundations Determine Resilience"
    },
    "bio": {
      "bg": "Dragomir Vatkov е опитен корпоративен архитект по киберсигурност с повече от 27 години опит в проектирането и управлението на бизнес-ориентирани архитектури за сигурност в средите на IT, OT и софтуерно-центрични продукти. Като водещ архитект по киберсигурност, той ръководи инициативи за сигурност чрез дизайн, основани на корпоративна архитектура и принципите на SABSA, гарантирайки, че киберсигурността е систематично вградена в дигиталните продукти, платформи и операции за постигане на осезаема бизнес стойност. Преди това Dragomir заемаше висши ръководни позиции в енергийния сектор и в разработката на продукти и услуги за киберсигурност. Притежава MSc от RWTH Aachen (Германия) и е SABSA Chartered Architect.",
      "en": "Dragomir is a seasoned Enterprise Cyber Security Architect with more than 27 years of experience designing and governing business-driven security architectures across IT, OT, and software-centric products environments. As Lead Cyber Security Architect, he leads security-by-design initiatives grounded in Enterprise Architecture and SABSA principles, ensuring cyber security is systematically embedded into digital products, platforms, and operations to deliver tangible business value. Previously, Dragomir held senior leadership roles in the Energy, Cyber Security Products and Services development Sectors. He holds an MSc. from RWTH Aachen (Germany), is a SABSA Chartered Architect, and combines deep architectural rigor with hands-on industry, product, and research experience."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "dragomir-vatkov.webp"
  },
  {
    "slug": "elitsa-encheva",
    "title": "проф. Елица Енчева, д.м. - BSTF 2026",
    "metaDesc": "BSTF 2026 - проф. Елица Енчева, д.м., Head of Radiation Oncology @ Medical University Varna",
    "name": {
      "bg": "проф. Елица Енчева, д.м.",
      "en": "Prof. Elitsa Encheva, MD, PhD"
    },
    "role": {
      "bg": "Head of Radiation Oncology @ Medical University Varna",
      "en": "Head of Radiation Oncology @ Medical University Varna"
    },
    "track": {
      "bg": "Биотехнологии",
      "en": "BioTech"
    },
    "topic": {
      "bg": "Радиационна онкология и медицинска иновация",
      "en": "Radiation oncology &amp; medical innovation"
    },
    "bio": {
      "bg": "Проф. Елица Енчева завършва Медицински университет - София през 2003 г. През 2009 г. придобива специалност по лъчелечение, а през 2011 г. - образователната и научна степен доктор от МУ-София. От 2013 г. е ръководител на новосъздаденото Отделение по лъчелечение в УМБАЛ „Света Марина” - Варна. През 2014 г. ѝ е присъдено академичното звание доцент, а през 2019 г. е избрана за професор в МУ-Варна. Член е на Българското дружество по лъчелечение, Българската асоциация по радиология (BAR), Европейското дружество по лъчетерапия и онкология (ESTRO) и Международното дружество по стереотаксична радиохирургия (ISRS). През 2016 г. е удостоена с Почетния знак на Българския лекарски съюз за принос в развитието и внедряването на иновативна медицина.",
      "en": "Prof. Elitsa Encheva graduated from the Medical University of Sofia in 2003. In 2009, she obtained her specialty in Radiation Oncology, and in 2011 she earned her PhD from the Medical University of Sofia. Since 2013, she has been Head of the Department of Radiation Oncology at St. Marina University Hospital, Varna. In 2014, she was awarded the academic title of Associate Professor, and in 2019 she was promoted to Full Professor at the Medical University of Varna. She is a member of the Bulgarian Society of Radiation Oncologists, the Bulgarian Association of Radiology (BAR), the European Society for Radiotherapy and Oncology (ESTRO), and the International Stereotactic Radiosurgery Society (ISRS). In 2016, Prof. Encheva was awarded the Honorary Badge of the Bulgarian Medical Association for her contribution to the development and implementation of innovative medicine."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "elitsa-encheva.jpg"
  },
  {
    "slug": "elitza-stoilova",
    "title": "Елица Стоилова - BSTF 2026",
    "metaDesc": "BSTF 2026 - Елица Стоилова, Co-founder &amp; CEO @ Umni | AI2B Zone",
    "name": {
      "bg": "Елица Стоилова",
      "en": "Elitza Stoilova"
    },
    "role": {
      "bg": "Co-founder &amp; CEO @ Umni | AI2B Zone",
      "en": "Co-founder &amp; CEO @ Umni | AI2B Zone"
    },
    "track": {
      "bg": "Изкуствен интелект",
      "en": "Artificial Intelligence"
    },
    "topic": {
      "bg": "AI чатботи в туризма: реален бизнес ефект",
      "en": "AI chatbots in tourism: real business impact"
    },
    "bio": {
      "bg": "Елица Стоилова е съосновател и CEO на Umni.bg - AI чатбот платформа за създаване и управление на AI чатботове за продажби, маркетинг, клиентска поддръжка, както и съосновател и експерт на AI агенция AI2B Zone (одит, консултации и обучения в сферата на AI). Тя има над 20 години опит в хотелиерството и туризма, с утвърдена кариера като маркетинг директор и генерален мениджър на хотели, туроператор и компания за недвижими имоти, управляваща хотели. Работила е в хотели в Турция, Тунис, Мароко и е развила кариера в хотелиерството за 17 години на о-в Сайпан, Северни Мариански острови (САЩ). Била е консултант по дестинационен маркетинг и председател на комитет към Marianas Visitors Authority (AdHoc, MVA) за над 10 години и е получила 2 награди от MVA за влиянието си върху развитието на дестинацията. Елица съосновава Umni.bg през 2017 г. по време на участието си в най-големия глобален стартъп акселератор, The Founder Institute (от Силициевата долина), с фокус върху чатботове. Тя е лектор в Software University с първия цялостен курс в България за AI чатботове. Сертифициран AEO специалист (оптимизация за AI видимост), AI консултант и обучител, чест гост като експерт в национални медии и лектор на конференции, публични събития и университети в България и Китай, където преподава \"AI в Туризма\". Автор е на рубриката \"AI Travel Economy\" в BGTourism.bg и на първия в България курс \"AEO за хотели\".",
      "en": "Elitza Stoilova is the co-founder and CEO of Umni - an AI chatbot platform for creating and managing AI chatbots for sales, marketing, customer support, and a co-founder and expert of AI Agency AI2B Zone (audit, consultancy and training in AI). Elitza has over 20 years of experience in the hospitality and tourism industry, with an established career as a Marketing Director and General Manager of hotels, tour operator and real estate company managing hotels. She has worked in hotels in Turkey, Tunisia, Morocco and has developed her career in the hospitality industry over 17 years on Saipan, Northern Mariana Islands (USA). She served as a destination marketing consultant and committee chair for the Marianas Visitors Authority (AdHoc, MVA) for over 10 years and received 2 awards from MVA for her impact on the destination development. Elitza co-founded Umni while participating in and successfully completing the largest global startup accelerator, The Founder Institute (by Silicon Valley), with a focus on chatbots in 2017. Elitza was lecturer at Software University with the first comprehensive course in Bulgaria on AI chatbots. She is certified AEO Specialist (AI visibility optimization), AI consultant and trainer, frequent guest as an expert in national media and speaker at conferences, public events and Universities in Bulgaria and China, where she teaches \"AI in Tourism\". She is an author of AI Travel Economy rubric at BGTourism.bg and the first in Bulgaria course \"AEO for hotels\"."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "elitza-stoilova.jpg"
  },
  {
    "slug": "georgi-dobrev",
    "title": "Георги Добрев - BSTF 2026",
    "metaDesc": "BSTF 2026 - Георги Добрев, Analyst @ ARC Fund",
    "name": {
      "bg": "Георги Добрев",
      "en": "Georgi Dobrev"
    },
    "role": {
      "bg": "Analyst @ ARC Fund",
      "en": "Analyst @ ARC Fund"
    },
    "track": {
      "bg": "Умен град",
      "en": "Smart City"
    },
    "topic": {
      "bg": "Дигитализация на МСП: анализ и политики",
      "en": "SME digitalization: analysis &amp; policy"
    },
    "bio": {
      "bg": "Георги Добрев работи като анализатор във Фондация за приложни изследвания и комуникации (ARC Fund), като се фокусира върху подкрепата за трансфер на технологии и дигитализация на МСП, устойчивото развитие на регионалната иновационна екосистема и приобщаването чрез интеграция на уязвими групи на пазара на труда. Той анализира и публикува по темите за иновациите, търговията и технологичната политика, използвайки количествени методи, които комбинират макроикономически статистики, финансови и анкетни данни. Георги допринася за ежегодния доклад Innovation.bg на ARC Fund, Глобалния годишник за конкурентоспособност на IMD World Competitiveness Centre и регулярните доклади на Global Trade and Innovation Policy Alliance.",
      "en": "Georgi Dobrev works as an analyst at the Applied Research and Communications Fund (ARC Fund), focusing on support for the technology transfer and the digitalisation of SMEs, the sustainable development of the regional innovation ecosystem, and employability through the integration of vulnerable groups into the labour market. He analyses and publishes on innovation, trade, and technology policy, using quantitative methods that combine macroeconomic statistics, financial and survey data. Georgi contributes to ARC Fund's annual Innovation.bg report, the Global Competitiveness Yearbook of the IMD World Competitiveness Centre, and the regular reports of the Global Trade and Innovation Policy Alliance."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "georgi-dobrev.jpg"
  },
  {
    "slug": "hristian-daskalov",
    "title": "д-р Христиан Даскалов - BSTF 2026",
    "metaDesc": "BSTF 2026 - д-р Христиан Даскалов, Cybersecurity Compliance Director | Chair @ DIH Trakia",
    "name": {
      "bg": "д-р Христиан Даскалов",
      "en": "Dr. Hristian Daskalov"
    },
    "role": {
      "bg": "Cybersecurity Compliance Director | Chair @ DIH Trakia",
      "en": "Cybersecurity Compliance Director | Chair @ DIH Trakia"
    },
    "track": {
      "bg": "Киберсигурност",
      "en": "Cybersecurity"
    },
    "topic": {
      "bg": "Европейски портфейли за цифрова самоличност: възможности и рискове",
      "en": "European digital identity wallets: opportunities and risks"
    },
    "bio": {
      "bg": "Д-р Христиан Даскалов е практикуващ специалист по киберсигурност, изследовател, университетски преподавател и съветник по дигитална политика с над 15 години опит в дигиталната трансформация, отворените технологии и регулаторните рамки за управление и устойчивост. В момента служи като директор по съответствие в областта на киберсигурността във водещ квалифициран доставчик на доверителни услуги. Преди това е съосновател на Центъра за споделена наука и бизнес (CSSB) към Техническия университет в София, където пилотира приложението на блокчейн технологиите в академичната среда. Между 2023 и 2026 г. е председател на Управителния съвет на Дигитален иновационен хъб Тракия (Cyber4AllSTAR), българския EDIH за киберсигурност, и координира ангажимента на Хъба по паневропейските инициативи CyberSec4OT и OSCRAT.EU. В това качество той подкрепя предоставянето на услуги за киберсигурност на индустриални МСП в цяла Европа и подпомага съответствието им с регулаторните рамки за киберсигурност, включително Европейския акт за киберустойчивост. Работата му е фокусирана върху изграждането на институционална и технологична устойчивост в дигитално зависими екосистеми, с акцент върху публично-частното сътрудничество, сигурното управление на жизнения цикъл на продуктите и изграждането на капацитет за кибер-осъзнати иновации.",
      "en": "Dr. Hristian DASKALOV is a cybersecurity practitioner, researcher, university lecturer, and digital policy advisor with over 15 years of experience in digital transformation, open technologies, and regulatory frameworks for governance and resilience. He currently serves as Cybersecurity Compliance Director at a leading qualified trust service provider. Previously, he co-founded the Center for Shared Science &amp; Business (CSSB) at the Technical University of Sofia, where he piloted the application of blockchain technologies in academia. Between 2023 and 2026, he served as Chairman of the Board of Digital Innovation Hub Trakia (Cyber4AllSTAR), Bulgaria's cybersecurity EDIH, and coordinated the Hub's engagement under the pan-European CyberSec4OT and OSCRAT.EU initiatives. In this capacity, he supported the provision of cybersecurity services to industrial SMEs across Europe and helped enable their compliance with cybersecurity regulatory frameworks, including the European Cyber Resilience Act. His work focuses on building institutional and technological resilience in digitally dependent ecosystems, with an emphasis on public-private collaboration, secure product lifecycle governance, and capacity building for cyber-aware innovation."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "hristian-daskalov.jpg"
  },
  {
    "slug": "kalina-tsolova",
    "title": "Калина Цолова - BSTF 2026",
    "metaDesc": "BSTF 2026 - Калина Цолова, Expert @ ARC Fund",
    "name": {
      "bg": "Калина Цолова",
      "en": "Kalina Tsolova"
    },
    "role": {
      "bg": "Expert @ ARC Fund",
      "en": "Expert @ ARC Fund"
    },
    "track": {
      "bg": "Умен град",
      "en": "Smart City"
    },
    "topic": {
      "bg": "Иновационни екосистеми и технологична устойчивост на градовете",
      "en": "Innovation ecosystems &amp; urban technology resilience"
    },
    "bio": {
      "bg": "Калина Цолова е експерт по иновации, регионално развитие и климатично-фокусирана градска трансформация с опит в публичния, частния и неправителствения сектор. В ARC Fund тя се фокусира върху развитието на иновационни екосистеми и технологично-базирани решения, които укрепват устойчивостта, конкурентоспособността на градовете и регионите. Калина организира диалога за сигурност и иновации на високо ниво - ангажимент на ARC Fund с иновационната общност на Силициевата долина и Маями, където работи с глобални технологични компании, инвеститори и академични институции по темите за бъдещето на AI, дигиталната инфраструктура и устойчивите вериги за доставки. Тя има задълбочено разбиране за връзката между дигиталната трансформация и индустриалната конкурентоспособност, с фокус върху позиционирането на Черноморския регион в развиващия се технологичен и енергиен пейзаж на Европа.",
      "en": "Kalina Tcolova is an expert in innovation, regional development, and climate-focused urban transformation, with experience in the public, private, and non-governmental sectors. At ARC Fund, she focuses on the development of innovation ecosystems and technology-driven solutions that strengthen the resilience, sustainability, and competitiveness of cities and regions. Kalina organizes the high-level Security and Innovation Dialogue - an ARC Fund engagement with the Silicon Valley and Miami innovation community, where she engages with global technology companies, investors, and academic institutions on the future of AI, digital infrastructure, and resilient supply chains. She brings a comprehensive understanding of the link between digital transformation and industrial competitiveness, with a focus on positioning the Black Sea region within Europe's evolving technology and energy landscape."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "kalina-tsolova.webp"
  },
  {
    "slug": "krastena-nikolova",
    "title": "проф. Кръстена Николова - BSTF 2026",
    "metaDesc": "BSTF 2026 - проф. Кръстена Николова, Full Professor of Biophysics @ Medical University Varna",
    "name": {
      "bg": "проф. Кръстена Николова",
      "en": "Prof. Krastena Nikolova"
    },
    "role": {
      "bg": "Full Professor of Biophysics @ Medical University Varna",
      "en": "Full Professor of Biophysics @ Medical University Varna"
    },
    "track": {
      "bg": "Биотехнологии",
      "en": "BioTech"
    },
    "topic": {
      "bg": "Биофизика и оптични методи в медицината",
      "en": "Biophysics &amp; optical methods in medicine"
    },
    "bio": {
      "bg": "Проф. Кръстена Николова завършва Физическия факултет на Пловдивския университет през 2001 г., а през 2002 г. придобива магистърска степен по Приложна математика. През 2007 г. защитава докторска дисертация по Физика в Централната лаборатория по оптично съхранение и обработка на информация при БАН. От 2002 до 2011 г. преминава през академичните длъжности асистент, старши асистент и главен асистент в Университета по хранителни технологии - Пловдив. През 2011 г. е избрана за доцент по Физика, а през 2016 г. - за доцент в Медицински университет - Варна. През 2018 г. е избрана за професор по Физика в МУ-Варна, а през 2019 г. придобива специалност по Биофизика.",
      "en": "Professor Krastena Nikolova graduated from the Faculty of Physics at Paisii Hilendarski University of Plovdiv in 2001. In 2002, she obtained a Master's degree in Applied Mathematics. In 2007, she was awarded her PhD in Physics from the Central Laboratory of Optical Storage and Processing of Information at the Bulgarian Academy of Sciences. From 2002 to 2011, she held academic positions from Assistant to Chief Assistant Professor at the University of Food Technologies, Plovdiv. In 2011, she was appointed Associate Professor of Physics, and in 2016 she joined the Medical University of Varna. In 2018, she was promoted to Full Professor of Physics at MU-Varna, and in 2019 she obtained a specialty qualification in Biophysics."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "krastena-nikolova.jpg"
  },
  {
    "slug": "kristina-bliznakova",
    "title": "проф. Кристина Близнакова - BSTF 2026",
    "metaDesc": "BSTF 2026 - проф. Кристина Близнакова, Associate Professor @ TU Varna | Medical University Varna",
    "name": {
      "bg": "проф. Кристина Близнакова",
      "en": "Prof. Kristina Bliznakova"
    },
    "role": {
      "bg": "Associate Professor @ TU Varna | Medical University Varna",
      "en": "Associate Professor @ TU Varna | Medical University Varna"
    },
    "track": {
      "bg": "Биотехнологии",
      "en": "BioTech"
    },
    "topic": {
      "bg": "Биомедицинско инженерство и AI в диагностиката на рак",
      "en": "Biomedical engineering &amp; AI in cancer diagnostics"
    },
    "bio": {
      "bg": "Проф. Кристина Близнакова завършва Електронна техника и микроелектроника в Технически университет - Варна през 1996 г. Между 1996 и 1998 г. посещава магистърска програма по Биомедицинско инженерство в Университета в Патрас, Гърция. През 2003 г. защитава докторска дисертация на тема \"Изследване и разработка на софтуерна симулация за рентгеново изображение\" в Университета в Патрас. От 2004 до 2012 г. ръководи изследователската група по Монте Карло симулации в Университета в Патрас. През 2012 г. получава престижната награда Marie Curie Career Integration Grant за реинтеграция в България. От 2016 г. е доцент в Технически университет - Варна, а от 2019 г. е член на катедрата по Медицинска техника в Медицински университет - Варна. На европейско ниво проф. Близнакова ръководи модула \"Антропоморфни фантоми\" в EUTEMPE-NET.",
      "en": "Professor Kristina Bliznakova graduated in Electronic Engineering and Microelectronics from the Technical University of Varna, Bulgaria, in 1996. Between 1996 and 1998, she attended the Master's Program in Biomedical Engineering at the University of Patras, Greece. In 2003, she successfully defended her PhD dissertation on \"software simulation for X-ray imaging\" at the University of Patras. From 2004 to 2012, she led the Monte Carlo Simulations Research Group at the University of Patras. In 2012, she was awarded a Marie Curie Career Integration Grant to support her reintegration into Bulgaria. Since 2016, she has served as Associate Professor at the Technical University of Varna, and since 2019 she has been a member of the Department of Medical Equipment at the Medical University of Varna. At the European level, Prof. Bliznakova serves as the leader of the Anthropomorphic Phantoms module within EUTEMPE-NET."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "kristina-bliznakova.webp"
  },
  {
    "slug": "kristina-eskenazi",
    "title": "Кристина Ескенази - BSTF 2026",
    "metaDesc": "BSTF 2026 - Кристина Ескенази, Chair @ Health &amp; Life Sciences Cluster Bulgaria",
    "name": {
      "bg": "Кристина Ескенази",
      "en": "Kristina Eskenazi"
    },
    "role": {
      "bg": "Chair @ Health &amp; Life Sciences Cluster Bulgaria",
      "en": "Chair @ Health &amp; Life Sciences Cluster Bulgaria"
    },
    "track": {
      "bg": "Биотехнологии",
      "en": "BioTech"
    },
    "topic": {
      "bg": "Бъдещето на здравеопазването: от изследвания към мащабни иновации",
      "en": "Future of Health &amp; Life Sciences: from research to scalable innovation"
    },
    "bio": {
      "bg": "Кристина Ескенази е председател на Клъстер Здравеопазване и Науки за Живота България и AI Cluster Bulgaria, вицепрезидент на Съвета на европейските биорегиони (CEBR) и член на Управителния съвет на КРИБ. Тя е съосновател на Spinoff Bulgaria и активно популяризира иновациите, биотехнологиите, изкуствения интелект и deep-tech предприемачеството в Европа.",
      "en": "Kristina Eskenazi is Chair of the Health &amp; Life Sciences Cluster Bulgaria and AI Cluster Bulgaria, Vice President of the Council of European BioRegions (CEBR), and Board Member of KRIB. She is co-founder of Spinoff Bulgaria and actively promotes innovation, biotechnology, AI, and deep-tech entrepreneurship in Europe."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "kristina-eskenazi.jpg"
  },
  {
    "slug": "martin-kuvandzhiev",
    "title": "Мартин Кувандиев - BSTF 2026",
    "metaDesc": "BSTF 2026 - Мартин Кувандиев, Founder @ Encorp | Co-founder, Bitcoin Gold",
    "name": {
      "bg": "Мартин Кувандиев",
      "en": "Martin Kuvandzhiev"
    },
    "role": {
      "bg": "Founder @ Encorp | Co-founder, Bitcoin Gold",
      "en": "Founder @ Encorp | Co-founder, Bitcoin Gold"
    },
    "track": {
      "bg": "Изкуствен интелект",
      "en": "Artificial Intelligence"
    },
    "topic": {
      "bg": "Blockchain, fintech и AI: следващата вълна на иновации",
      "en": "Blockchain, fintech &amp; AI: the next innovation wave"
    },
    "bio": {
      "bg": "Мартин Кувандиев е основател на Encorp, водещ доставчик на fintech, blockchain и healthcare решения, с над 10 години опит в създаването и мащабирането на иновативни проекти, които използват най-съвременни технологии. Encorp расте с 2x годишно от 2019 г., благодарение на талантлив екип от над 30 професионалисти и разнообразно портфолио от клиенти и партньори. Той е и съосновател на Bitcoin Gold, една от водещите криптовалути на пазара, и blockchain консултант за няколко други ventures като TokaCity. С опит в софтуерното развитие, той е печелил множество NASA Space Apps Challenges и е разработвал награждавани приложения за iOS и други платформи.",
      "en": "As the founder of Encorp, a leading fintech, blockchain and healthcare solutions provider, Martin has over ten years of experience in creating and scaling innovative projects that leverage cutting-edge technology and business acumen. Encorp has been growing 2x yearly since 2019, thanks to our talented team of 30+ professionals and our diverse portfolio of clients and partners. He is also a co-founder of Bitcoin Gold, one of the top cryptocurrencies in the market, and a blockchain advisor for several other ventures, such as TokaCity. With a background in software development and programming, he has won multiple NASA Space Apps Challenges and developed award-winning applications for iOS and other platforms."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "martin-kuvandzhiev-2.png"
  },
  {
    "slug": "ruslan-stefanov",
    "title": "Руслан Стефанов - BSTF 2026",
    "metaDesc": "BSTF 2026 - Руслан Стефанов, Director Strategy &amp; Innovation @ ARC Fund",
    "name": {
      "bg": "Руслан Стефанов",
      "en": "Ruslan Stefanov"
    },
    "role": {
      "bg": "Director Strategy &amp; Innovation @ ARC Fund",
      "en": "Director Strategy &amp; Innovation @ ARC Fund"
    },
    "track": {
      "bg": "Умен град",
      "en": "Smart City"
    },
    "topic": {
      "bg": "20 години Innovation.bg: картата на иновациите в България",
      "en": "20 years Innovation.bg: mapping Bulgaria's innovation landscape"
    },
    "bio": {
      "bg": "Руслан Стефанов е директор по стратегия и иновации във Фондация за приложни изследвания и комуникации (ARC Fund). Той ръководи изследователската, проектната и консултантската дейност на ARC Fund в областта на интелигентната специализация, регионалните иновационни стратегии, технологичните и иновационни оценки и подкрепата за иновационно-ориентирани предприятия в Югоизточна Европа и Черноморския регион. Руслан е председател и редактор на Innovation.bg, най-престижната годишна оценка на иновационното представяне на българската икономика през последните 20 години, и член на журито на Националния награден фонд за иновации. Той е член на Global Trade and Innovation Policy Alliance и на MIT REAP Bulgaria екипа.",
      "en": "Ruslan Stefanov is the Director for Strategy and Innovation at the Applied Research and Communications Fund (ARC Fund). He leads ARC Fund's research, project management and consulting work on smart specialization, regional innovation strategies, technology and innovation assessments and innovation-driven enterprise support and scale up in Southeast Europe and the Black Sea region. Ruslan is chair and editor of Innovation.bg, the most reputable annual assessment of the innovation performance of the Bulgarian economy over the past 20 years, and a member of the jury of the National Innovation Award. He is a member of the Global Trade and Innovation Policy Alliance and the MIT REAP Bulgaria team."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "ruslan-stefanov.jpg"
  },
  {
    "slug": "svetlin-stoyanov",
    "title": "Светлин Стоянов - BSTF 2026",
    "metaDesc": "BSTF 2026 - Светлин Стоянов, Executive Director @ MTG Dolphin Shipyard | Chair @ BULNAS",
    "name": {
      "bg": "Светлин Стоянов",
      "en": "Svetlin Stoyanov"
    },
    "role": {
      "bg": "Executive Director @ MTG Dolphin Shipyard | Chair @ BULNAS",
      "en": "Executive Director @ MTG Dolphin Shipyard | Chair @ BULNAS"
    },
    "track": {
      "bg": "Морски технологии",
      "en": "Marine Tech"
    },
    "topic": {
      "bg": "Корабостроенето на Черно море: иновации и предизвикателства",
      "en": "Black Sea shipbuilding: innovation &amp; challenges"
    },
    "bio": {
      "bg": "Светлин Стоянов е изпълнителен директор на корабостроителница MTG Dolphin във Варна, България. Той е председател на Управителния комитет на Българската национална асоциация по корабостроене и кораборемонт (BULNAS), член на Управителния съвет на Конфедерацията на работодателите и индустриалците в България (КРИБ) и член на Управителния съвет на Българската камара за корабоплаване. Член е и на Надзорния съвет на Морско училище, както и на ABS Black Sea технически комитет и BV Hellenic and Black Sea Technical Committee. Г-н Стоянов е завършил Висшето морско училище - Варна и притежава MSc от Морска академия, Варна.",
      "en": "Svetlin Stoyanov is Executive Director of MTG Dolphin Shipyard in Varna, Bulgaria. He is Chairman of the Managing Committee of Bulgarian National Association of Shipbuilding and Ship repair (BULNAS), Member of the Board of Confederation of Employers and Industrialists in Bulgaria (CEIB) and Member of the Board of Bulgarian Chamber of Shipping. He stays at the Supervisory board of the Naval Academy as well and a Member of ABS Black Sea technical committee and BV Hellenic and Black Sea Technical Committee. Mr. Stoyanov has graduated from the High Maritime School-Varna and holds a MSc from the Naval Academy, Varna."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "svetlin-stoyanov.webp"
  },
  {
    "slug": "teade-punter",
    "title": "Dr. Teade Punter - BSTF 2026",
    "metaDesc": "BSTF 2026 - Dr. Teade Punter, Leading Professor, AI for Society @ Fontys University",
    "name": {
      "bg": "Dr. Teade Punter",
      "en": "Dr. Teade Punter"
    },
    "role": {
      "bg": "Leading Professor, AI for Society @ Fontys University",
      "en": "Leading Professor, AI for Society @ Fontys University"
    },
    "track": {
      "bg": "Изкуствен интелект",
      "en": "Artificial Intelligence"
    },
    "topic": {
      "bg": "Интеграция на умни системи",
      "en": "Smart System Integration"
    },
    "bio": {
      "bg": "Dr. Ir. Teade Punter е професор (лектор) по High Tech Embedded Software в Университета за приложни науки Fontys, Айндховен, Нидерландия. Неговата изследователска група прави приложни изследвания в областта на data engineering, digital twinning и AI за разработка на интелигентни системи. Фокусът на групата HTES е също върху киберсигурността в кибер-физическите системи. Teade е и водещ професор за Fontys' Centre of Expertise AI for Society, в който 7 изследователски групи си сътрудничат по различни аспекти на AI, като AI инженеринг и ELSA. Преди да се присъедини към Fontys, Teade беше research fellow в TNO Embedded Systems Initiative, knowledge manager в Embedded Systems Institute, консултант по формални методи в Laboratory of Quality Software на Технологичния университет в Айндховен, group leader и competence manager във Fraunhofer IESE в Кайзерслаутерн и course teamleader в Отворения университет на Нидерландия.",
      "en": "Dr.Ir. Teade Punter is a professor (lector) in High Tech Embedded Software at Fontys University of Applied Science, Eindhoven, the Netherlands. His research group does applied research on data engineering, digital twinning and AI for smart systems development. The focus of the HTES group is also on Cybersecurity in Cyber Physical Systems. Teade is also leading professor for the Fontys' Centre of Expertise AI for Society, in which 7 research groups cooperate on various aspects of AI, like AI engineering and ELSA. Before he joined Fontys, Teade was research fellow at TNO Embedded Systems Initiative, knowledge manager at Embedded Systems Institute, consultant Formal Methods at Laboratory of Quality Software of Eindhoven University of Technology, groupleader and competence manager at Fraunhofer IESE in Kaiserslautern and course teamleader at the Open University of the Netherlands."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "teade-punter.webp"
  },
  {
    "slug": "trifon-tsekov",
    "title": "Трифон Цеков - BSTF 2026",
    "metaDesc": "BSTF 2026 - Трифон Цеков, CEO @ 3-Fi Medical",
    "name": {
      "bg": "Трифон Цеков",
      "en": "Trifon Tsekov"
    },
    "role": {
      "bg": "CEO @ 3-Fi Medical",
      "en": "CEO @ 3-Fi Medical"
    },
    "track": {
      "bg": "Биотехнологии",
      "en": "BioTech"
    },
    "topic": {
      "bg": "От изолирани данни до клинични доказателства: федерирано обучение в медицинския AI",
      "en": "From Data Silos to Clinical Evidence: Federated Learning for Medical AI"
    },
    "bio": {
      "bg": "Трифон Цеков е CEO на 3-Fi Medical, бивш директор на хардуерни R&amp;D и radar системен архитект с над 10 години опит във вградени системи, обработка на сигнали в реално време и надежден отбранителен хардуер. Член на AI Cluster Bulgaria, той прилага високонадеждно инженерство за регулирани медицински AI решения.",
      "en": "Trifon Tsekov is CEO of 3-Fi Medical, a former Director of Hardware R&amp;D and radar systems architect with 10+ years in embedded systems, real-time signal processing, and rugged defence hardware. An AI Cluster Bulgaria member, he applies high-reliability engineering to regulated medical AI."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "trifon-tsekov.jpg"
  },
  {
    "slug": "yasen-tanev",
    "title": "Ясен Танев - BSTF 2026",
    "metaDesc": "BSTF 2026 - Ясен Танев, Cybersecurity Expert @ DIH Trakia",
    "name": {
      "bg": "Ясен Танев",
      "en": "Yasen Tanev"
    },
    "role": {
      "bg": "Cybersecurity Expert @ DIH Trakia",
      "en": "Cybersecurity Expert @ DIH Trakia"
    },
    "track": {
      "bg": "Киберсигурност",
      "en": "Cybersecurity"
    },
    "topic": {
      "bg": "Помощ, а не тежест: Как да превърнем регулаторните изисквания в реална киберсигурност",
      "en": "Help, Not Burden: How to Transform Regulatory Requirements into Real Cybersecurity"
    },
    "bio": {
      "bg": "Ясен Танев е експерт по киберсигурност и информационна сигурност в Дигитален иновационен хъб Тракия, специализирайки в регулаторни рамки и съответствие. Притежава богат опит в прилагането на стратегии за киберсигурност, включващи NIS2, AI Act и Cyber Resilience Act.",
      "en": "Yasen Tanev is a cybersecurity and information security expert at Digital Innovation Hub Trakia, specializing in regulatory frameworks and compliance. He has extensive experience in implementing cybersecurity strategies involving NIS2, AI Act and Cyber Resilience Act."
    },
    "metaDate": {
      "bg": "21-22 ноември 2026",
      "en": "November 21-22, 2026"
    },
    "metaLocation": {
      "bg": "Варна, България",
      "en": "Varna, Bulgaria"
    },
    "image": "yasen-tanev.jpg"
  }
]
;